Repository meta-mingles/metamingle-server, pull requests merged in 2023-10, with the labels that each got.

#13 Feature/script [Script] entity 설계, 기본 클래스 생성
  build.gradle
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/temp.java
  src/main/java/com/mingles/metamingle/script/command/application/controller/ScriptCommandController.java
  src/main/java/com/mingles/metamingle/script/command/application/dto/request/CreateScriptRequest.java
  src/main/java/com/mingles/metamingle/script/command/application/dto/response/ScriptCommandResponse.java
  src/main/java/com/mingles/metamingle/script/command/application/service/ScriptCommandService.java
  src/main/java/com/mingles/metamingle/script/command/domain/aggregate/entity/Script.java
  src/main/java/com/mingles/metamingle/script/command/domain/aggregate/vo/ScriptMemberNoVO.java
  src/main/java/com/mingles/metamingle/script/command/domain/aggregate/vo/ShortFormNoVO.java
  src/main/java/com/mingles/metamingle/script/command/domain/repository/ScriptCommandRepository.java
  src/main/java/com/mingles/metamingle/script/command/domain/service/ScriptCommandDomainService.java
  src/main/java/com/mingles/metamingle/script/command/infrastructure/service/ScriptCommandInfraService.java
  src/main/java/com/mingles/metamingle/script/query/application/controller/temp.java
  src/main/java/com/mingles/metamingle/script/query/application/dto/temp.java
  src/main/java/com/mingles/metamingle/script/query/application/service/temp.java
  src/main/java/com/mingles/metamingle/script/query/infrastructure/repository/temp.java
  src/main/java/com/mingles/metamingle/script/query/infrastructure/service/temp.java
Labels: 🦄Feat, 🎁setting

#20 Feature/member [Member] query domain - service, repository 생성
  src/main/java/com/mingles/metamingle/member/query/application/dto/request/FindMemberRequest.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/response/MemberQueryResponse.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/temp.java
  src/main/java/com/mingles/metamingle/member/query/application/service/MemberQueryService.java
  src/main/java/com/mingles/metamingle/member/query/application/service/temp.java
  src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/MemberQueryRepository.java
  src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/temp.java
Labels: 🦄Feat

#21 Feature/shortform [ShortForm] 숏폼 CRUD
  .gitignore
  build.gradle
  src/main/java/com/mingles/metamingle/configuration/AwsS3Config.java
  src/main/java/com/mingles/metamingle/configuration/FirebaseConfig.java
  src/main/java/com/mingles/metamingle/interativemovie/command/domain/aggregate/entity/InteractiveMovie.java
  src/main/java/com/mingles/metamingle/interativemovie/command/domain/aggregate/vo/MemberNoVO.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/request/DeleteShortFormRequest.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/request/ShortFormCreateRequest.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/CreateShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/DeleteShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/ShortFormCreateResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormCommandService.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
  src/main/java/com/mingles/metamingle/shortform/command/domain/aggregate/entity/ShortForm.java
  src/main/java/com/mingles/metamingle/shortform/command/domain/aggregate/vo/MemberNoVO.java
  src/main/java/com/mingles/metamingle/shortform/command/domain/service/ShortFormCommandDomainService.java
  src/main/java/com/mingles/metamingle/shortform/command/domain/service/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/application/controller/ShortFormQueryController.java
  src/main/java/com/mingles/metamingle/shortform/query/application/controller/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/request/GetShortFormListRequest.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java
  src/main/java/com/mingles/metamingle/shortform/query/domain/service/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiMemberQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/temp.java
  src/main/resources/db.data/data.sql
  src/main/resources/temp.yml
Labels: 🦄Feat

#25 feature : #24 shortForm 조회 시 interactiveMovie 정보 함께 반환
  src/main/java/com/mingles/metamingle/interativemovie/query/domain/repository/InteractiveMovieQueryRepository.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/request/DeleteShortFormRequest.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/CreateShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/DeleteShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/InteractiveMovieDTO.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiInteractiveMovieService.java
Labels: 🦄Feat

#27 Feature/interactive [InteractiveMovie] response, request, data.sql, 임시 memberNo 설정
  src/main/java/com/mingles/metamingle/interativemovie/command/application/dto/response/CreateInteractiveMovieResponse.java
  src/main/java/com/mingles/metamingle/interativemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/interativemovie/query/application/dto/response/GetInteractiveMovieResponse.java
  src/main/resources/db.data/data.sql
Labels: 🦄Feat, 🔧refactor

#23 Feature/script [Script] 대본 Command Controller & Service
  src/main/java/com/mingles/metamingle/member/query/application/service/MemberQueryService.java
  src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/MemberQueryRepository.java
  src/main/java/com/mingles/metamingle/script/command/application/controller/ScriptCommandController.java
  src/main/java/com/mingles/metamingle/script/command/application/dto/request/CreateScriptRequest.java
  src/main/java/com/mingles/metamingle/script/command/application/dto/response/ScriptCommandResponse.java
  src/main/java/com/mingles/metamingle/script/command/application/dto/response/ScriptInfraResponse.java
  src/main/java/com/mingles/metamingle/script/command/application/service/ScriptCommandService.java
  src/main/java/com/mingles/metamingle/script/command/domain/aggregate/entity/Script.java
  src/main/java/com/mingles/metamingle/script/command/domain/service/ScriptCommandDomainService.java
  src/main/java/com/mingles/metamingle/script/command/infrastructure/service/ScriptCommandInfraService.java
  src/main/resources/db/data/data.sql
  src/test/java/com/mingles/metamingle/command/application/service/ScriptCommandServiceTests.java
Labels: 🦄Feat

#36 feature : #35 shortForm 전체 조회 정렬 변경
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java
Labels: 🦄Feat

#38 Feature/script 대본 Command 서비스, 컨트롤러
  src/main/java/com/mingles/metamingle/script/query/application/controller/ScriptQueryController.java
  src/main/java/com/mingles/metamingle/script/query/application/controller/temp.java
  src/main/resources/db/data/data.sql
Labels: 🦄Feat

#44 refactoring : #43 인터랙티브 무비 통신 방법 수정
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
Labels: 🔧refactor

#45 Feature/shortform 영상 삭제 로직 추가
  build.gradle
  src/main/java/com/mingles/metamingle/configuration/FirebaseConfig.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/domain/repository/InteractiveMovieCommandRepository.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/infrastructure/service/ApiShortFormService.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/DeleteShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
  src/main/java/com/mingles/metamingle/shortform/command/infrastructure/service/ApiInteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/shortform/command/infrastructure/service/temp.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiInteractiveMovieQueryService.java
Labels: 🦄Feat

#46 feature : #35 숏폼 전체 조회 정렬 변경 (최신순)
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java
Labels: 🦄Feat
