Repository meta-mingles/metamingle-server, pull requests merged in 2023-11, with the labels that each got.

#58 feature : #57 인터랙티브 무비 저장, 숏폼 조회 오류
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
Labels: 🐞bugfix

#61 feature : #59 숏폼 전체 조회 데이터 변경
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
Labels: 🦄Feat

#62 Feature/shortform : data.sql 더미 데이터 변경
  src/main/resources/db/data/data.sql
Labels: 🦄Feat

#64 feature : #63 shortForm List & 상세 조회 시 좋아요 수 & 좋아요 여부 조회
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormListResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/GetShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/query/application/dto/response/ShortFormLikeInfoDTO.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiShortFormLikeQueryService.java
Labels: 🦄Feat

#70 Feature/login 회원가입/로그인 기능 구현
  build.gradle
  src/main/java/com/mingles/metamingle/auth/CustomAuthenticationFilter.java
  src/main/java/com/mingles/metamingle/auth/Jwt401Handler.java
  src/main/java/com/mingles/metamingle/auth/Jwt403Handler.java
  src/main/java/com/mingles/metamingle/auth/JwtTokenProvider.java
  src/main/java/com/mingles/metamingle/configuration/CorsConfig.java
  src/main/java/com/mingles/metamingle/configuration/JwtSecurityConfig.java
  src/main/java/com/mingles/metamingle/configuration/SecurityConfig.java
  src/main/java/com/mingles/metamingle/member/command/application/controller/MemberCommandController.java
  src/main/java/com/mingles/metamingle/member/command/application/controller/temp.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/RegistMemberRequest.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/response/MemberCommandResponse.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/response/temp.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/temp.java
  src/main/java/com/mingles/metamingle/member/command/application/service/MemberCommandService.java
  src/main/java/com/mingles/metamingle/member/command/application/service/temp.java
  src/main/java/com/mingles/metamingle/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/mingles/metamingle/member/command/domain/aggregate/entity/Role.java
  src/main/java/com/mingles/metamingle/member/command/domain/aggregate/entity/temp.java
  src/main/java/com/mingles/metamingle/member/command/domain/aggregate/vo/temp.java
  src/main/java/com/mingles/metamingle/member/command/domain/repository/MemberCommandRepository.java
  src/main/java/com/mingles/metamingle/member/command/domain/repository/temp.java
  src/main/java/com/mingles/metamingle/member/query/application/controller/MemberQueryController.java
  src/main/java/com/mingles/metamingle/member/query/application/controller/temp.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/request/LoginRequest.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/response/LoginResponse.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/response/MemberQueryResponse.java
  src/main/java/com/mingles/metamingle/member/query/application/service/MemberQueryService.java
  src/main/java/com/mingles/metamingle/member/query/infrastructure/repository/MemberQueryRepository.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiMemberQueryService.java
  src/main/resources/db/data/data.sql
Labels: 🦄Feat

#81 Feature/shortform : 헤더에 있는 토큰으로 사용자를 구별하도록 수정
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/infrastructure/service/ApiShortFormService.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
  src/main/java/com/mingles/metamingle/shortform/query/application/controller/ShortFormQueryController.java
Labels: 🦄Feat

#85 feature : #82 토큰으로 사용자 구별하도록 수정
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
Labels: 🦄Feat

#86 feature : #83 토큰으로 사용자 구별하도록 수정
  src/main/java/com/mingles/metamingle/shortformlike/command/application/controller/ShortFormLikeCommandController.java
  src/main/java/com/mingles/metamingle/shortformlike/query/application/controller/ShortFormLikeQueryController.java
Labels: 🦄Feat

#87 feature : #84 토큰으로 사용자 구별하도록 수정
  src/main/java/com/mingles/metamingle/movielike/command/application/controller/InteractiveMovieLIkeCommandController.java
  src/main/java/com/mingles/metamingle/movielike/query/application/controller/InteractiveMovieLikeQueryController.java
Labels: 🦄Feat

#89 Feature/mongodb: Creative Tool 이용시 필요한 이미지, 사운드 데이터 조회
  src/main/java/com/mingles/metamingle/configuration/MongoDBConfig.java
  src/main/java/com/mingles/metamingle/creativetool/document/Image.java
  src/main/java/com/mingles/metamingle/creativetool/document/Sound.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/controller/CreativeToolController.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/request/ImageRequest.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/request/SoundRequest.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/ImageResponse.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/SoundResponse.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/service/CreativeToolService.java
  src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/ImageRepository.java
  src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/SoundRepository.java
  src/main/java/com/mingles/metamingle/scenario/command/application/controller/ScenarioCommandController.java
  src/main/java/com/mingles/metamingle/scenario/command/application/dto/request/SaveScenarioRequest.java
  src/main/java/com/mingles/metamingle/scenario/command/application/service/ScenarioCommandService.java
  src/main/java/com/mingles/metamingle/scenario/command/domain/aggregate/document/Scenario.java
  src/main/java/com/mingles/metamingle/scenario/command/domain/mongo/ScenarioCommandRepository.java
  src/main/java/com/mingles/metamingle/scenario/command/infrastructure/service/ScenarioCommandInfraService.java
  src/test/java/com/mingles/metamingle/command/application/service/ScenarioCommandServiceTests.java
Labels: 🦄Feat

#93 Feature/shortform : 영상 생성 기능의 RequestHeader 임시 삭제
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
Labels: 🦄Feat

#95 feature : #94 인터랙티브 무비 저장 오류 수정
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/resources/db/data/data.sql
Labels: 🐞bugfix

#99 Feature/creative tool 실시간 스트리밍 및 이미지/BGM 몽고DB 연동
  src/main/java/com/mingles/metamingle/configuration/SecurityConfig.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/controller/CreativeToolController.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/ImageResponse.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/dto/response/SoundResponse.java
  src/main/java/com/mingles/metamingle/creativetool/query/application/service/CreativeToolService.java
  src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/ImageRepository.java
  src/main/java/com/mingles/metamingle/creativetool/query/domain/mongo/SoundRepository.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/RegistMemberRequest.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/response/MemberCommandResponse.java
  src/main/java/com/mingles/metamingle/member/command/application/service/MemberCommandService.java
  src/main/java/com/mingles/metamingle/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/mingles/metamingle/member/query/application/dto/response/MemberQueryResponse.java
  src/main/java/com/mingles/metamingle/scenario/command/application/controller/ScenarioCommandController.java
  src/main/java/com/mingles/metamingle/scenario/command/application/dto/response/BGMResponse.java
  src/main/java/com/mingles/metamingle/scenario/command/application/dto/response/BgImageResponse.java
  src/main/java/com/mingles/metamingle/scenario/command/domain/service/ScenarioCommandDomainService.java
  src/main/java/com/mingles/metamingle/scenario/command/infrastructure/service/ScenarioCommandInfraService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiMemberQueryService.java
Labels: 🦄Feat, ✏️rename, 🔧refactor

#102 Feature/redis - 회원가입 시 이메일로 본인인증 & 레디스 설정
  build.gradle
  src/main/java/com/mingles/metamingle/configuration/RedisConfig.java
  src/main/java/com/mingles/metamingle/member/command/application/controller/MemberCommandController.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/MailAuthRequest.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/RegistMemberRequest.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/response/MailAuthResponse.java
  src/main/java/com/mingles/metamingle/member/command/application/service/MemberCommandService.java
  src/main/java/com/mingles/metamingle/member/command/infrastructure/service/MailService.java
  src/main/java/com/mingles/metamingle/member/command/infrastructure/service/RedisService.java
  src/main/java/com/mingles/metamingle/member/command/infrastructure/service/temp.java
  src/main/resources/templates/mail.html
Labels: 🦄Feat

#105 feature : #103 퀴즈 Entity, 기본 클래스 생성
  src/main/java/com/mingles/metamingle/quiz/command/application/controller/QuizCommandController.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/response/temp.java
  src/main/java/com/mingles/metamingle/quiz/command/application/service/QuizCommandService.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/aggregate/entity/Quiz.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/aggregate/vo/ShortFormNoVO.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/repository/QuizCommandRepository.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/service/QuizCommandDomainService.java
  src/main/java/com/mingles/metamingle/quiz/command/infrastructure/repository/temp.java
  src/main/java/com/mingles/metamingle/quiz/command/infrastructure/service/QuizInfraCommandService.java
  src/main/java/com/mingles/metamingle/quiz/query/application/controller/QuizQueryController.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/response/temp.java
  src/main/java/com/mingles/metamingle/quiz/query/application/service/QuizQueryService.java
  src/main/java/com/mingles/metamingle/quiz/query/domain/repository/QuizQueryRepository.java
  src/main/java/com/mingles/metamingle/quiz/query/domain/service/QuizQueryDomainService.java
  src/main/java/com/mingles/metamingle/quiz/query/infrastructure/repository/temp.java
  src/main/java/com/mingles/metamingle/quiz/query/infrastructure/service/QuizInfraQueryService.java
Labels: 🦄Feat

#109 Feature/avatar - 엔티티 수정 및 조회/저장/수정 로직 구현
  src/main/java/com/mingles/metamingle/avatar/command/application/controller/AvatarCommandController.java
  src/main/java/com/mingles/metamingle/avatar/command/application/controller/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/application/dto/request/AvatarCommandRequest.java
  src/main/java/com/mingles/metamingle/avatar/command/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/application/dto/response/AvatarCommandResponse.java
  src/main/java/com/mingles/metamingle/avatar/command/application/dto/response/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/application/dto/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/application/service/AvatarCommandService.java
  src/main/java/com/mingles/metamingle/avatar/command/application/service/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/Avatar.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/vo/AvatarMemberNoVO.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/vo/temp.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/repository/AvatarCommandRepository.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/repository/temp.java
  src/main/java/com/mingles/metamingle/avatar/query/application/controller/AvatarQueryController.java
  src/main/java/com/mingles/metamingle/avatar/query/application/controller/temp.java
  src/main/java/com/mingles/metamingle/avatar/query/application/dto/response/AvatarQueryResponse.java
  src/main/java/com/mingles/metamingle/avatar/query/application/dto/temp.java
  src/main/java/com/mingles/metamingle/avatar/query/application/service/AvatarQueryService.java
  src/main/java/com/mingles/metamingle/avatar/query/application/service/temp.java
  src/main/java/com/mingles/metamingle/avatar/query/infrastructure/repository/AvatarQueryRepository.java
  src/main/java/com/mingles/metamingle/avatar/query/infrastructure/repository/temp.java
Labels: 🦄Feat

#115 Feature/quiz - 퀴즈 생성 & 아바타 통신 & 회원가입 수정
  src/main/java/com/mingles/metamingle/avatar/command/application/controller/AvatarCommandController.java
  src/main/java/com/mingles/metamingle/avatar/command/application/service/AvatarCommandService.java
  src/main/java/com/mingles/metamingle/avatar/command/domain/aggregate/entity/Avatar.java
  src/main/java/com/mingles/metamingle/avatar/query/application/controller/AvatarQueryController.java
  src/main/java/com/mingles/metamingle/avatar/query/application/dto/response/AvatarQueryResponse.java
  src/main/java/com/mingles/metamingle/avatar/query/application/service/AvatarQueryService.java
  src/main/java/com/mingles/metamingle/member/command/application/controller/MemberCommandController.java
  src/main/java/com/mingles/metamingle/member/command/application/dto/request/RegistMemberTemp.java
  src/main/java/com/mingles/metamingle/member/command/application/service/MemberCommandService.java
  src/main/java/com/mingles/metamingle/member/query/application/controller/MemberQueryController.java
  src/main/java/com/mingles/metamingle/quiz/command/application/controller/QuizCommandController.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/request/QuizCommandRequest.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/response/QuizCommandInfraResponse.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/response/QuizCommandResponse.java
  src/main/java/com/mingles/metamingle/quiz/command/application/dto/response/temp.java
  src/main/java/com/mingles/metamingle/quiz/command/application/service/QuizCommandService.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/aggregate/entity/Quiz.java
  src/main/java/com/mingles/metamingle/quiz/command/infrastructure/service/QuizInfraCommandService.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/response/QuizQueryResponse.java
  src/main/java/com/mingles/metamingle/scenario/command/infrastructure/service/ScenarioCommandInfraService.java
Labels: 🦄Feat, 🔧refactor

#118 feature : #117 interactive 관련 컨트롤러에 requestHeaader 추가
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/interactivemovie/query/application/controller/InteractiveMovieQueryController.java
  src/main/java/com/mingles/metamingle/movielike/command/application/controller/InteractiveMovieLIkeCommandController.java
  src/main/java/com/mingles/metamingle/movielike/query/application/controller/InteractiveMovieLikeQueryController.java
Labels: 🦄Feat

#121 Feature/shortform
  build.gradle
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/dto/VideoData.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/dto/VideoMetadata.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/dto/response/CreateInteractiveMovieResponse.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/dto/response/SubtitledVideo.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/dto/response/UploadVideo.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/domain/aggregate/entity/InteractiveMovie.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/infrastructure/service/ApiShortFormService.java
  src/main/java/com/mingles/metamingle/interactivemovie/query/application/controller/InteractiveMovieQueryController.java
  src/main/java/com/mingles/metamingle/interactivemovie/query/application/service/InteractiveMovieQueryService.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/CreateShortFormResponse.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/SubtitledVideo.java
  src/main/java/com/mingles/metamingle/shortform/command/application/dto/response/UploadVideo.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
  src/main/java/com/mingles/metamingle/shortform/command/domain/aggregate/entity/ShortForm.java
  src/main/java/com/mingles/metamingle/shortform/command/infrastructure/service/ApiInteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/shortform/query/application/controller/ShortFormQueryController.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormQueryService.java
  src/main/java/com/mingles/metamingle/shortform/query/infrastructure/service/ApiInteractiveMovieQueryService.java
  src/main/resources/db/data/data.sql
Labels: 🦄Feat

#123 Feature/quiz stat - 퀴즈 랭킹 추출 및 DB 업데이트 설정
  src/main/java/com/mingles/metamingle/MetaMingleApplication.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/quiz/command/application/service/QuizCommandService.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/aggregate/entity/Quiz.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/aggregate/entity/QuizRank.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/repository/QuizCommandRepository.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/repository/RankCommandRepository.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/service/QuizCommandDomainService.java
  src/main/java/com/mingles/metamingle/quiz/command/domain/service/RankScheduler.java
  src/main/java/com/mingles/metamingle/quiz/query/application/controller/QuizQueryController.java
  src/main/java/com/mingles/metamingle/quiz/query/application/controller/QuizRankQueryController.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/request/temp.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/response/QuizQueryResponse.java
  src/main/java/com/mingles/metamingle/quiz/query/application/dto/response/QuizRankQueryResponse.java
  src/main/java/com/mingles/metamingle/quiz/query/application/service/QuizQueryService.java
  src/main/java/com/mingles/metamingle/quiz/query/application/service/QuizRankQueryService.java
  src/main/java/com/mingles/metamingle/quiz/query/domain/repository/QuizQueryRepository.java
  src/main/java/com/mingles/metamingle/quiz/query/domain/repository/RankQueryRepository.java
  src/main/java/com/mingles/metamingle/scenario/command/infrastructure/service/ScenarioCommandInfraService.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/query/application/service/ShortFormRankService.java
  src/main/java/com/mingles/metamingle/shortform/query/domain/repository/ShortFormQueryRepository.java
  src/main/java/com/mingles/metamingle/shortformlike/command/domain/aggregate/entity/ShortFormLike.java
  src/main/java/com/mingles/metamingle/shortformlike/command/domain/repository/ShortFormLikeCommandRepository.java
  src/main/java/com/mingles/metamingle/shortformlike/query/domain/repository/ShortFormLikeQueryRepository.java
  src/main/resources/db/data/data.sql
Labels: 🦄Feat

#126 Feature/shortform : [ShortForm][InteractiveMovie] 한글/영어자막 영상, 병합 오류 해결
  build.gradle
  src/main/java/com/mingles/metamingle/MetaMingleApplication.java
  src/main/java/com/mingles/metamingle/configuration/CorsConfig.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/controller/InteractiveMovieCommandController.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/application/service/InteractiveMovieCommandService.java
  src/main/java/com/mingles/metamingle/interactivemovie/command/infrastructure/service/ApiShortFormService.java
  src/main/java/com/mingles/metamingle/interactivemovie/query/application/controller/InteractiveMovieQueryController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/controller/ShortFormCommandController.java
  src/main/java/com/mingles/metamingle/shortform/command/application/service/ShortFormFirebaseService.java
  src/main/java/com/mingles/metamingle/shortform/query/application/controller/ShortFormQueryController.java
Labels: 🐞bugfix, 🦄Feat

#133 Feature/jenkins : 젠킨스 연동, CI/CD
  Dockerfile
  Jenkinsfile
  build.gradle
  src/main/java/com/mingles/metamingle/global/configuration/FirebaseConfig.java
  src/main/java/com/mingles/metamingle/global/infra/AiInfraService.java
  src/test/java/com/mingles/metamingle/MetaMingleApplicationTests.java
Labels: 🦄Feat
